name: Security - Trivy

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-fs:
    name: Trivy FS (repo)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trivy FS scan (vuln+misconfig+secrets)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          scanners: 'vuln,misconfig,secret'
          format: 'sarif'
          output: 'trivy-fs.sarif'

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-fs.sarif'

  trivy-image:
    name: Trivy Image (matrix)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - 'sonarqube:latest'
          - 'node:20'
    steps:
      - name: Trivy image scan (${{ matrix.image }})
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ matrix.image }}
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-image-${{ matrix.image }}.sarif'

      - name: Upload SARIF to GitHub Security tab (image)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-${{ matrix.image }}.sarif'

